# Generated by Django 5.1.4 on 2024-12-28 21:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vaga', '0007_endereco_created_at_endereco_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ong',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_fantasia', models.CharField(max_length=255)),
                ('razao_social', models.CharField(blank=True, max_length=255, null=True)),
                ('cnpj', models.CharField(max_length=14)),
                ('telefone', models.CharField(help_text='Contato de um responsável da ONG.', max_length=11)),
                ('site', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('Ativa', 'Ativa'), ('Inativa', 'Inativa'), ('Em análise', 'Em análise')], max_length=50)),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vaga.endereco')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ong',
            },
        ),
    ]
