# Generated by Django 5.1.4 on 2024-12-29 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_alter_ong_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='ong',
            name='email',
            field=models.EmailField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
