# Generated by Django 5.1.4 on 2025-01-03 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_remove_ong_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ong',
            name='cnpj',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
