# Generated by Django 5.1.4 on 2025-01-08 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_alter_ong_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ong',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Em análise', 'Em análise'), ('Ativa', 'Ativa'), ('Inativa', 'Inativa')], default='Pendente', max_length=50),
        ),
    ]
