# Generated by Django 5.1.4 on 2025-01-09 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_alter_ong_status'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ong',
            table='ongs',
        ),
    ]
