# Generated by Django 5.1.4 on 2025-04-24 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0010_voluntario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ong',
            name='nome_fantasia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
