# Generated by Django 5.1.4 on 2025-04-27 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0011_alter_ong_nome_fantasia'),
    ]

    operations = [
        migrations.AddField(
            model_name='ong',
            name='status_cnpj',
            field=models.CharField(default='Não informado', max_length=20),
        ),
    ]
