# Generated by Django 5.1.4 on 2025-04-30 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0012_ong_status_cnpj'),
    ]

    operations = [
        migrations.AddField(
            model_name='ong',
            name='resumo',
            field=models.TextField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='voluntario',
            name='resumo',
            field=models.TextField(default='', max_length=5000),
        ),
    ]
