# Generated by Django 5.1.4 on 2025-05-01 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0013_ong_resumo_voluntario_resumo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ong',
            name='resumo',
            field=models.TextField(default=' ', max_length=5000),
        ),
    ]
