# Generated by Django 5.1.4 on 2025-05-04 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0014_alter_ong_resumo'),
    ]

    operations = [
        migrations.RunSQL(
            sql="CREATE UNIQUE INDEX user_email_unique ON auth_user (email);",
            reverse_sql="DROP INDEX user_email_unique;"
        ),
    ]
