# Generated by Django 5.1.4 on 2025-05-26 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0016_reconhecimentofacial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reconhecimentofacial',
            table='reconhecimentos_faciais',
        ),
    ]
