# Generated by Django 5.1.4 on 2024-12-14 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(help_text='Título da vaga', max_length=100)),
                ('descricao', models.TextField(help_text='Descrição da vaga', max_length=5000)),
                ('requisitos', models.TextField(help_text='Requisitos da vaga', max_length=2500)),
                ('local', models.CharField(help_text='Endereço do trabalho', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
