# Generated by Django 5.1.4 on 2024-12-16 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaga', '0002_alter_vaga_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga',
            name='preenchida',
            field=models.BooleanField(default=False),
        ),
    ]
