# Generated by Django 5.1.4 on 2024-12-27 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaga', '0004_endereco_remove_vaga_local_vaga_id_endereco'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vaga',
            old_name='id_endereco',
            new_name='endereco',
        ),
    ]
