# Generated by Django 5.1.4 on 2024-12-27 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaga', '0005_rename_id_endereco_vaga_endereco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='complemento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
