# Generated by Django 5.1.4 on 2025-01-09 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaga', '0007_endereco_created_at_endereco_updated_at'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='endereco',
            table='enderecos',
        ),
        migrations.AlterModelTable(
            name='vaga',
            table='vagas',
        ),
    ]
