# Generated by Django 5.1.4 on 2025-01-26 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaga', '0010_rename_usuario_vaga_ong'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaga',
            name='endereco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vaga.endereco'),
        ),
    ]
