# Generated by Django 5.1.4 on 2025-02-15 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaga', '0012_alter_vaga_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vaga',
            options={'permissions': (('visualizar_minhas_vagas', 'ONG visualizar as suas vagas.'),)},
        ),
    ]
