# Generated by Django 5.1.4 on 2025-02-18 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0010_voluntario'),
        ('vaga', '0013_alter_vaga_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidatura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Aceito', 'Aceito'), ('Recusado', 'Recusado')], default='Pendente', max_length=50)),
                ('candidato', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.voluntario')),
                ('vaga', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vaga.vaga')),
            ],
            options={
                'db_table': 'candidaturas',
            },
        ),
    ]
