# Generated by Django 5.1.4 on 2025-02-18 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaga', '0014_candidatura'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidatura',
            old_name='candidato',
            new_name='voluntario',
        ),
    ]
