# Generated by Django 5.1.4 on 2025-03-11 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaga', '0016_vaga_quantidade_vagas'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga',
            name='encerrada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vaga',
            name='fim_candidaturas',
            field=models.DateField(help_text='Encerramento das candidaturas', null=True),
        ),
    ]
