# Generated by Django 5.1.4 on 2025-03-18 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaga', '0017_vaga_encerrada_vaga_fim_candidaturas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaga',
            name='encerrada',
        ),
    ]
