# Generated by Django 5.1.4 on 2025-04-02 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaga', '0018_remove_vaga_encerrada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordenadas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.FloatField(max_length=20)),
                ('longitude', models.FloatField(max_length=20)),
            ],
            options={
                'db_table': 'coordenadas',
            },
        ),
        migrations.AddField(
            model_name='endereco',
            name='coordenadas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vaga.coordenadas'),
        ),
    ]
