# Generated by Django 5.1.4 on 2025-04-02 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaga', '0019_coordenadas_endereco_coordenadas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endereco',
            name='coordenadas',
        ),
        migrations.AddField(
            model_name='endereco',
            name='latitude',
            field=models.FloatField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='endereco',
            name='longitude',
            field=models.FloatField(blank=True, max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Coordenadas',
        ),
    ]
