# Generated by Django 5.1.4 on 2025-04-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaga', '0020_remove_endereco_coordenadas_endereco_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga',
            name='area',
            field=models.CharField(choices=[('Animais', 'Animais'), ('Apoio Psicológico', 'Apoio Psicológico'), ('Assistência Social', 'Assistência Social'), ('Captação de Recursos / Marketing Social', 'Captação de Recursos / Marketing Social'), ('Cultura e Arte', 'Cultura e Arte'), ('Direiros Humanos', 'Direiros Humanos'), ('Educação', 'Educação'), ('Esporte e Lazer', 'Esporte e Lazer'), ('Inclusão Social', 'Inclusão Social'), ('Meio Ambiente', 'Meio Ambiente'), ('Outros', 'Outros'), ('Saúde', 'Saúde'), ('Tecnologia', 'Tecnologia')], default='Outros', max_length=50),
        ),
    ]
